### ISSUE TITLE
superflat

### ISSUE THREAD

**Issue by veroweewoo** [Harleyoc1/ChunkAnimator#1]
this mod works perfectly on all of my worlds but i noticed it doesnt on superflats, not sure why

**Comment by Harleyoc1** [comment]
Huh, that’s odd. I never even thought to test it on flat worlds but I’m also able to recreate this so I’ll look into it.

**Comment by Harleyoc1** [comment]
I looked into it and this also happens in 1.12. It’s because the chunk animation is starting at where it’s ending - so they just appear without any animation. 

If you change the mode to 1 you will see that the animation works fine, and the chunks fall out of the air. 

A simple solution is to just force mode 1 if the player is on a flat world, or I could force the animation to start from a lower value on a flat world. 

However I’ve now found that because of the way Minecraft renders chunks (I won’t even try to explain why lol), setting the animation to start lower doesn’t help, so I think the best option here (at least unless I or anyone else can find a way around this, but I don’t think it’d be worth the time anyway) is to force mode 1 on flat worlds.

**Comment by Harleyoc1** [comment]
FYI this (sort of) fix was removed (see #9). If you want a way to use flat worlds and have the animation work use one of the flat world presets where the ground is higher.
