### ISSUE TITLE
Request to update version of the mod for 1.8.9 to 1.3.7

### ISSUE THREAD

**Issue by Ihsan101** [Harleyoc1/ChunkAnimator#36]
1.8.9 Has one of the biggest download amounts for this mod, and I think one last update so that we can use this mod while using shaders would be greatly helpful to all players using this mod. Thank you.

**Comment by Harleyoc1** [comment]
Are you sure shaders don't work for this version? I thought that in versions 1.12.2 and less it worked with shaders without any special compatibility. 

Regardless I don't have the time to be updating versions this old. It's not a version of Forge I'm familiar with modding. Also, of course the older versions have the biggest download counts, it's because they've been around the longest - doesn't mean they're still getting high volumes of downloads (and I highly doubt this for 1.8).
