### ISSUE TITLE
Chunk Animator Not Always Appear From Below In Server.

### ISSUE THREAD

**Issue by FikiAlis** [Harleyoc1/ChunkAnimator#9]
Bug:
Using chunk animator in server on low vertical chunk appear from below but when i get higher vertical chunk appear from above. I would like to see it appear from below all time because in the video below it look terrifying to watch. I'm not sure if the issue appear in single player because I never spend time there.

Video:
https://imgur.com/a/SvBl5Dz

Minecraft Version: 1.16.4
Forge Version: 35.0.15
Chunk Animator Version: 1.2.2

**Comment by Harleyoc1** [comment]
That's odd, I never noticed that when testing and I have used this version on a server myself. I'll take a look into it.

**Comment by FikiAlis** [comment]
Try Visit Any Map/Server That Has High Vertical Build Maybe Like Parkour Map?
Also The World In The Video Everything Is Void/0 But Just That Island.

**Comment by Harleyoc1** [comment]
Ah! That will be why. As a remedy to #1 I fixed any worlds with void fog at y = 0 to go to mode 1 so that the animation plays in flat worlds (since the animation doesn't play because the land is so low). I'll find another way of identifying "true" flat worlds.

**Comment by Harleyoc1** [comment]
[ChunkAnimator-1.16.5-1.2.3.jar.zip](https://github.com/Harleyoc1/ChunkAnimator/files/6069312/ChunkAnimator-1.16.5-1.2.3.jar.zip)

Could you try this for me on void worlds? It checks for the `flatWorld` property instead of the void fog height (I didn't originally do that because it requires an access transformer). I'm not entirely sure if it will work since void worlds could be using the flat world property to make the void fog height at that level, but it's worth a try. 

If not, I'll just revert the flat world fix. I'd say the chunk animation working on servers that use void worlds is more important than it working on flat worlds. That or I could make a config option.

**Comment by Harleyoc1** [comment]
Either way the fact they are changing the void fog hight will break animation mode 2 as well, since that uses void fog height as the value to calculate which chunks should render from above or below. 

Also by the way I just noticed your version of Forge. This is very old, you should probably update it!

**Comment by FikiAlis** [comment]
alrighty ill try~ let see from both singleplayer and multiplayer.. ill record

**Comment by FikiAlis** [comment]
Still Same Thing Happened. Updated Both Mod And Forge.

1) Video: https://i.imgur.com/F6U4C9b.mp4
    Left - Server | Right - Client World
2) ModList: https://i.imgur.com/C2HlV4c.png
   Some of these mod used for server staff monitoring work purpose.
   I don't think any of these mod is incompatible

Minecraft Version: 1.16.4
Forge Version: 35.1.4
Chunk Animator Version: 1.2.3

**Comment by Harleyoc1** [comment]
OK, I thought that might be the case. I'll just remove the flat world thing, it's not really necessary anyway. Only reason I added it was because I thought it wouldn't affect anything else but it's probably better that flat worlds just don't have the upward animation for that the default height (I guess if it really bothers people they could just use one of the presets that makes the world spawn higher). 

FYI the only reason I can't do anything about the upward animation on default flat worlds is because Minecraft doesn't seem to be able to render chunks below y = 0 (this might be fixed in 1.17 if they use the same flat world height, but I doubt they will).
